name: pytest

on: [push, pull_request]

jobs:
  test-on-env:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-13]
        python-version: ["3.10", "3.11", "3.12"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.7
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flit
          flit install --deps=develop
      - name: Test with pytest
        run: |
          pip install pytest
          pip install numpy
          pytest tests